name: macOS CI

on: push

env:
  TRAVIS_OS_NAME: osx
  LLVM_CONFIG: /usr/local/opt/llvm/bin/llvm-config
  PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig

jobs:
  test_macos:
    runs-on: macos-latest
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v2

      - name: Prepare System
        run: bin/ci prepare_system

      - name: Prepare Build
        run: bin/ci prepare_build

      - name: Test
        run: bin/ci build

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          report_paths: .junit/*.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
